# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-18 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newblog', '0004_auto_20170418_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='intro',
            field=models.CharField(max_length=250, verbose_name='Интро'),
        ),
    ]
