# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-18 09:36
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('newblog', '0006_auto_20170418_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpagetag',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='newblog.BlogPage'),
        ),
    ]
