# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-18 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newblog', '0010_auto_20170418_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpagetag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
